export enum DbRoles {
  ADMIN = 'Администратор',
  // USER = 'user',
  // SPECIALIST = 'specialist',
  LABORATORY = 'Лаборант',
  TECHNOLOGIST = 'Технолог',
  PLANNER = 'Планировщик',
  REPORTS = 'Отчеты',
  EMPLOYERS = 'Сотрудники',
  // TEST = 'Тест',
  GODMODE = 'Godmode',
  WGHT_GODMODE = 'Ред. взвешиваний',
  FOREMAN = 'Мастер',
  CARDS = 'Карточки',
  WEIGHER = 'Весовой участок',
  TRACE = 'Прослеживаемость',
}
