FROM node:18-alpine

WORKDIR /dash

COPY ./dash/package*.json ./
COPY ./dash/tsconfig*.json ./
COPY ./dash/vite.config*.json ./
COPY ./dash/src ./src
RUN npm ci
COPY ./dash .
RUN npm run build
RUN npm i -g http-server
CMD ["http-server", "-p3000", "./dist"]
