FROM node:18-alpine

WORKDIR /workstation

COPY ./workstation/package*.json ./
COPY ./workstation/tsconfig*.json ./
COPY ./workstation/vite.config*.json ./
COPY ./workstation/src ./src
RUN npm ci
COPY ./workstation .
RUN npm run build
RUN npm i -g http-server
CMD ["http-server", "-p3000", "./dist"]
