

FROM node:18-alpine as build-step

WORKDIR /application

ENV PATH /application/node_modules/.bin:$PATH

COPY ./application/package*.json ./
COPY ./application/tsconfig*.json ./
COPY ./application/vite.config*.json ./
COPY ./application/src ./src
COPY ./application/public ./public
COPY ./application/index.html ./
RUN npm ci
RUN npm run build

FROM nginx:stable
COPY --from=build-step /application/dist /usr/share/nginx/html
COPY docker/application/nginx.conf /etc/nginx/nginx.conf
