export enum RouteNames {
  HOME = '/',
  LOGIN = '/login',
  FORBIDDEN = '/forbidden',
  SUMMARY_UPLOAD = '/summary_upload',
  // SUMMARY_LIST = '/summary_list',
  SUMMARY_DETAIL = '/summary/:summary_id',
  // RECORD_DETAIL = '/record/:record_id',
  LABORATORY = '/laboratory',
  CONVEYORS = '/conveyors',
  DOCUMENTS = '/documents',
  // DASH = '/dash',

  // REPORTS = "/reports",
  // ADMIN = '/admin',
  // FORBIDDEN = "/forbidden",
  // USERS = "/admin/users",
  // TECHNOLOGIST = '/technologist',
  // PLANNER = "/planner",

  // REPORT1 = "/reports/1",
  EMPLOYERS = '/employers',
  BOILS_LIST = '/boils_list',
  BOILS_REPORT = '/boils_report',
  TIME_REPORT = '/time_report',
  // SUMMARY_REPORT = '/summary_report',
  FOREMAN = '/foreman',
  // FOREMAN_NEW = "/foreman_new",
  USERS_LIST = '/users_list',
  BASES_UPDATE = '/bases_update',
  // TUBE_RECORDS_UPLOAD = '/tube_records_upload',
  UI_PAGE = '/ui_page',
  // REGULATIONS_UPSERT = '/regulations_upsert',
  CANS_DASH = '/cans_dash',
  CANS_LIST = '/cans_list',
  CANS_LOCATION = 'cans_location',
  INVENTORIES = '/inventories/',
  INVENTORY_DETAIL = '/inventories/:inventory_id',
  TRACE_TRADEMARKS = '/trace_trademarks',
  TRACE_BATCHS = '/trace_batchs/',
  TRACE_BATCH_DETAIL = '/trace_batchs/:batch_id',
  TRACE_WGHT_REPORT = '/trace_wght_report',
  TRACE_WGHT_REPORT_DETAIL = '/trace_wght_report/detail',
  TRACE_WGHT_SUMMARY = '/trace_wght_summary',
  TRACE_WGHT_SUMMARY_DETAIL = '/trace_wght_summary_detail',
  TRACE_UPLOAD_BOILS = '/trace_upload_boils',
}
